### PR TITLE
Add journal article number and page count

### PR DESCRIPTION
**Pull request by vaitkus**
This PR introduces two bibliography-related data items addition of which were requested at the IUCr website:
* `_journal_article_number` (https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_journal_article_number).
* `_journal_article_page_count` (https://www.iucr.org/resources/cif/dictionaries/new-item/cif_core/_journal_article_page_count).

I slightly renamed the data items to follow the naming conventions of other data items:
* `_journal_article_number` to `_journal.paper_number` to match `_journal.paper_DOI`.
* `_journal_article_page_count` to `_journal.paper_pages` to match `_journal.suppl_publ_pages`.

Of course, the original names could be used if preferred.

### CODE REVIEW

**Comment by jamesrhester** [comment]
This looks good and straightforward, but perhaps the journal people at IUCr Chester should double-check. Calling @publcif and @nautolycus.

**Comment by publcif** [comment]
I don't foresee any problems for the IUCr Journals.

**Comment by merkys** [comment]
Thank you for adding these items!

**Comment by nautolycus** [comment]
Sorry, a bit slow to respond, but just to flag that I have returned from
my travels and will hope to catch up on outstanding matters in the near
future.

I have no objection to these changes.

Regards
Brian (nautolycus)

**Pull request merged**
