### PR TITLE
_type.source of many other SU items changed from `Related`

### PR DESCRIPTION
**Pull request by rowlesmr**
Split from #431

A bunch of SU data items' _type.source was Related, which doesn't seem to link up with the description of Related, so I changed them all to match the _type.source of the data item to which the SU belongs.

### CODE REVIEW

**Comment by vaitkus** [comment]
@jamesrhester , do you have any insights on the topic? Should the SU items have the `Related` purpose or should the inherit it from the measurand item?

**Comment by jamesrhester** [comment]
`_type.source` is `Related` because the su items are `_name.linked_item_id` to the dataname they are the SU of, so therefore they are `Related` to that data name. This makes sense to me, but I note this use of `Related` is not described explicitly.

**Comment by rowlesmr** [comment]
This also means that every other SU item I didn't touch is wrong, as well as the `general_su` save frame in `templ_attr.cif`.

**Comment by jamesrhester** [comment]
I've decided that I think `_type.source` of "same as linked data name" is appropriate (as this PR suggests). It's not a strong opinion, as in any case the information provided is redundant.

**Comment by jamesrhester** [comment]
Rejecting as per discussion in #434

**Pull request closed without merging**
