### PR TITLE
Move around cell 2

### PR DESCRIPTION
**Pull request by jamesrhester**
This replaces #299, dealing with issue #294  . Please refer to the discussion in those places for information. This PR provides nothing new compared to #299 , it just accounts for the updates to master.

Because of the reordering of the definitions, the usual Github diff looks very messy. The semantic changes are in commit 339aaa7 , so probably best to look at that to understand the changes. The commit after that *only* changes the order and pretty-prints.

### CODE REVIEW

**Comment by jamesrhester** [comment]
If @vaitkus and other commenters are happy with the current version, I'd like to merge so that we can proceed with a proper release of core CIF. Please advise.

**Comment by vaitkus** [comment]
@jamesrhester thank you for the work and sorry for not responding sooner. As discussed, I added two examples files that illustrate the new approach to recording cell measurement details based on the discussions in #299. Please check if they are ok. The single block example files currently invents a few data names (e.g. `_diffrn_radiation.diffrn_id`), places several Set category items in a loop (`_diffrn.ambient_temperature`) and groups a few items items from different categories in a single loop (e.g. `_diffrn_radiation_wavelength.value`), but I guess that some of these restrictions can be lifted in future commits.

Once you are happy with these examples, it would be nice if some other stakeholders could review them as well. I will ask some of my colleagues from the COD to take a look, but maybe there are some other database/IUCr archive people who would be affected by this that you are aware of?

**Comment by jamesrhester** [comment]
I have updated the examples to clarify a few things.

>Once you are happy with these examples, it would be nice if some other stakeholders could review them as well. I will ask some of my colleagues from the COD to take a look, but maybe there are some other database/IUCr archive people who would be affected by this that you are aware of?

This change is a logical extension of the multi-block approach that was discussed at length. What I propose doing is, as part of the release process, providing a proper description of all the changes (perhaps as a wiki page) and inviting everybody on COMCIFS/Core-DMG/cif-developers to review what has been written about those changes. Reviewers would have a few weeks to comment.

**Comment by vaitkus** [comment]
Ok, so from your updated comment in the `cell-measurement-merged-block.cif` example file I understood that I misinterpreted the general approach and went slightly overboard by trying to force the merged data block representation into the multi-block paradigm. Since the `CELL_MEASUREMENT` items are only deprecated and not outright removed, the COD can still keep using them to represent old archival files and will eventually adapt to process the multi-block files. If you also see no additional value from the custom audit schema introduced in `cell-measurement-merged-block.cif`, I suggest that we remove this file before the merge as to not confuse the readers with needless extra details.

On a related note, I added an example that uses the deprecated items and tried to highlight the benefits of the multi-block approach.

Finally, I will probably add the superflous `_definition_replaced.id` items just to silence the validator for now. I promise to remove them once the validator is patched.

If you are good with these changes, I am happy to merge.

**Comment by jamesrhester** [comment]
I'm happy with those changes, so I think we are ready to merge?

**Review by vaitkus — APPROVED** [review]

**Comment by vaitkus** [comment]
Great. @jamesrhester, should I merge it or will you?

**Comment by jamesrhester** [comment]
Thanks everybody for your contributions to this very complicated PR!

**Pull request merged**
