### PR TITLE
Changed atomic labels to type 'Word' for conformance with DDL1

### LINKED ISSUE #245: Items have become case-insensitive in DDLm core relative to DDL1
Both `_atom_site.label` and `_space_group_symop.id` are case-sensitive in DDL1 but have type `Code` in the DDLm dictionary, which means they are case-insensitive. I propose reverting these and any other such changes to be case-sensitive.

### PR DESCRIPTION
**Pull request by jamesrhester**
Closes #245

### CODE REVIEW

**Comment by jamesrhester** [comment]
So I've gone through the list and made a best guess as to the case-sensitivity of external identifiers. For the others I've tended to err on the side of case-sensitivity for conformance with DDL1.

**Comment by vaitkus** [comment]
Great, thank you for the work.

One last questions -- wouldn't it be better to leave the content type of `_publ_manuscript_incl_extra.item` data item as `Tag` instead of changing it to `Word`? CIF tags (data names) are case-insensitive and the `Tag` content type provides some additional value validation (requires the item to start with an underscore).

**Comment by jamesrhester** [comment]
My reading of the definition suggested that more than one tag could be included in this list. Actually 'Word' is also incorrect in that case, it should be just 'Text', I'll fix that now.

**Comment by vaitkus** [comment]
Great, thank you for the multiple iterations of changes.

**Pull request merged**
